"""
SDK fixtures derived from OpenAPI examples in src/openapi/spec.ts.

Generated by scripts/generate-sdk-fixtures.ts — do not edit by hand.
Run `pnpm generate:sdk:fixtures` after changing OpenAPI examples.
"""

from typing import Any, Dict

OPENAPI_FIXTURES: Dict[str, Any] = {
    "responses": {
        "GET / → 200": {
            "application/json": {
                "default": {
                    "success": True,
                    "data": {
                        "name": "Fluxora Backend",
                        "version": "0.1.0",
                        "docs": "/docs",
                    },
                    "meta": {
                        "timestamp": "2026-01-01T00:00:00.000Z",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /health → 200": {
            "application/json": {
                "default": {
                    "status": "ok",
                    "service": "fluxora-backend",
                    "network": "testnet",
                    "timestamp": "2026-01-01T00:00:00.000Z",
                },
            },
        },
        "GET /health → 503": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "SERVICE_UNAVAILABLE",
                        "message": "Service temporarily unavailable",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /health/ready → 200": {
            "application/json": {
                "default": {
                    "status": "healthy",
                    "version": "0.1.0",
                    "dependencies": {
                        "database": "healthy",
                        "redis": "healthy",
                    },
                },
            },
        },
        "GET /health/ready → 503": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "SERVICE_UNAVAILABLE",
                        "message": "One or more dependencies are unhealthy",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /health/live → 200": {
            "application/json": {
                "default": {
                    "success": True,
                    "data": {
                        "report": {
                            "status": "healthy",
                            "version": "0.1.0",
                            "uptimeSeconds": 12345,
                            "dependencies": {
                                "database": "healthy",
                                "redis": "healthy",
                            },
                        },
                    },
                    "meta": {
                        "timestamp": "2026-01-01T00:00:00.000Z",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /health/live → 500": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "INTERNAL_ERROR",
                        "message": "An unexpected error occurred",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /api/streams → 200": {
            "application/json": {
                "firstPage": {
                    "success": True,
                    "data": {
                        "streams": [
                            {
                                "id": "stream-aaa111",
                                "sender": "GAAZI4TCR3TY5OJHCTJC2A4QSY6CJWJH5IAJTGKIN2ER7LBNVKOCCWN",
                                "recipient": "GCEZWKCA5VLDNRLN3RPRJMRZOX3Z6G5CHCGZCP2J7F1NRQKQOHP3OGN",
                                "depositAmount": "1000000.0000000",
                                "streamedAmount": "0.0000000",
                                "remainingAmount": "1000000.0000000",
                                "ratePerSecond": "0.0000116",
                                "startTime": 1700000000,
                                "endTime": 0,
                                "status": "active",
                                "contractId": "api-created",
                                "transactionHash": "0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b",
                                "eventIndex": 0,
                                "createdAt": "2026-01-01T00:00:00.000Z",
                                "updatedAt": "2026-01-01T00:00:00.000Z",
                            },
                        ],
                        "has_more": True,
                        "next_cursor": "eyJ2IjoxLCJsYXN0SWQiOiJzdHJlYW0tYWFhMTExIn0",
                    },
                    "meta": {
                        "timestamp": "2026-01-01T00:00:00.000Z",
                        "requestId": "req_abc123",
                    },
                },
                "nextPage": {
                    "success": True,
                    "data": {
                        "streams": [
                            {
                                "id": "stream-bbb222",
                                "sender": "GAAZI4TCR3TY5OJHCTJC2A4QSY6CJWJH5IAJTGKIN2ER7LBNVKOCCWN",
                                "recipient": "GCEZWKCA5VLDNRLN3RPRJMRZOX3Z6G5CHCGZCP2J7F1NRQKQOHP3OGN",
                                "depositAmount": "500000.0000000",
                                "streamedAmount": "0.0000000",
                                "remainingAmount": "500000.0000000",
                                "ratePerSecond": "0.0000058",
                                "startTime": 1700001000,
                                "endTime": 0,
                                "status": "active",
                                "contractId": "api-created",
                                "transactionHash": "1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c",
                                "eventIndex": 1,
                                "createdAt": "2026-01-01T00:01:00.000Z",
                                "updatedAt": "2026-01-01T00:01:00.000Z",
                            },
                        ],
                        "has_more": True,
                        "next_cursor": "eyJ2IjoxLCJsYXN0SWQiOiJzdHJlYW0tYmJiMjIyIn0",
                    },
                    "meta": {
                        "timestamp": "2026-01-01T00:01:00.000Z",
                        "requestId": "req_bcd234",
                    },
                },
                "lastPage": {
                    "success": True,
                    "data": {
                        "streams": [
                            {
                                "id": "stream-zzz999",
                                "sender": "GAAZI4TCR3TY5OJHCTJC2A4QSY6CJWJH5IAJTGKIN2ER7LBNVKOCCWN",
                                "recipient": "GCEZWKCA5VLDNRLN3RPRJMRZOX3Z6G5CHCGZCP2J7F1NRQKQOHP3OGN",
                                "depositAmount": "250000.0000000",
                                "streamedAmount": "0.0000000",
                                "remainingAmount": "250000.0000000",
                                "ratePerSecond": "0.0000029",
                                "startTime": 1700002000,
                                "endTime": 1800000000,
                                "status": "completed",
                                "contractId": "api-created",
                                "transactionHash": "2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d",
                                "eventIndex": 2,
                                "createdAt": "2026-01-01T00:02:00.000Z",
                                "updatedAt": "2026-01-01T00:03:00.000Z",
                            },
                        ],
                        "has_more": False,
                        "next_cursor": None,
                    },
                    "meta": {
                        "timestamp": "2026-01-01T00:02:00.000Z",
                        "requestId": "req_cde345",
                    },
                },
            },
        },
        "GET /api/streams → 400": {
            "application/json": {
                "invalidCursor": {
                    "success": False,
                    "error": {
                        "code": "VALIDATION_ERROR",
                        "message": "cursor must be a valid opaque pagination token",
                    },
                },
                "invalidLimit": {
                    "success": False,
                    "error": {
                        "code": "VALIDATION_ERROR",
                        "message": "limit must be at most 100",
                    },
                },
            },
        },
        "GET /api/streams → 503": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "SERVICE_UNAVAILABLE",
                        "message": "Service temporarily unavailable",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "POST /api/streams → 201": {
            "application/json": {
                "default": {
                    "success": True,
                    "data": {
                        "id": "stream-abc123",
                        "sender": "GAAZI4TCR3TY5OJHCTJC2A4QSY6CJWJH5IAJTGKIN2ER7LBNVKOCCWN",
                        "recipient": "GCEZWKCA5VLDNRLN3RPRJMRZOX3Z6G5CHCGZCP2J7F1NRQKQOHP3OGN",
                        "depositAmount": "1000000.0000000",
                        "streamedAmount": "0.0000000",
                        "remainingAmount": "1000000.0000000",
                        "ratePerSecond": "0.0000116",
                        "startTime": 1700000000,
                        "endTime": 0,
                        "status": "active",
                        "contractId": "api-created",
                        "transactionHash": "0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b",
                        "eventIndex": 0,
                        "createdAt": "2026-01-01T00:00:00.000Z",
                        "updatedAt": "2026-01-01T00:00:00.000Z",
                    },
                    "meta": {
                        "timestamp": "2026-01-01T00:00:00.000Z",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "POST /api/streams → 400": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "VALIDATION_ERROR",
                        "message": "Request validation failed",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "POST /api/streams → 401": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "UNAUTHORIZED",
                        "message": "Authentication required to access this resource",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "POST /api/streams → 409": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "CONFLICT",
                        "message": "Resource conflict",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "POST /api/streams → 503": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "SERVICE_UNAVAILABLE",
                        "message": "Service temporarily unavailable",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /api/streams/{id} → 200": {
            "application/json": {
                "default": {
                    "success": True,
                    "data": {
                        "stream": {
                            "id": "stream-abc123",
                            "sender": "GAAZI4TCR3TY5OJHCTJC2A4QSY6CJWJH5IAJTGKIN2ER7LBNVKOCCWN",
                            "recipient": "GCEZWKCA5VLDNRLN3RPRJMRZOX3Z6G5CHCGZCP2J7F1NRQKQOHP3OGN",
                            "depositAmount": "1000000.0000000",
                            "streamedAmount": "0.0000000",
                            "remainingAmount": "1000000.0000000",
                            "ratePerSecond": "0.0000116",
                            "startTime": 1700000000,
                            "endTime": 0,
                            "status": "active",
                            "contractId": "api-created",
                            "transactionHash": "0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b",
                            "eventIndex": 0,
                            "createdAt": "2026-01-01T00:00:00.000Z",
                            "updatedAt": "2026-01-01T00:00:00.000Z",
                        },
                    },
                    "meta": {
                        "timestamp": "2026-01-01T00:00:00.000Z",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /api/streams/{id} → 404": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "NOT_FOUND",
                        "message": "Resource not found",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /api/streams/{id} → 503": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "SERVICE_UNAVAILABLE",
                        "message": "Service temporarily unavailable",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "DELETE /api/streams/{id} → 200": {
            "application/json": {
                "default": {
                    "success": True,
                    "data": {
                        "message": "Stream cancelled",
                        "id": "stream-abc123",
                    },
                    "meta": {
                        "timestamp": "2026-01-01T00:00:00.000Z",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "DELETE /api/streams/{id} → 401": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "UNAUTHORIZED",
                        "message": "Authentication required to access this resource",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "DELETE /api/streams/{id} → 404": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "NOT_FOUND",
                        "message": "Resource not found",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "DELETE /api/streams/{id} → 409": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "CONFLICT",
                        "message": "Resource conflict",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "DELETE /api/streams/{id} → 503": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "SERVICE_UNAVAILABLE",
                        "message": "Service temporarily unavailable",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "HEAD /api/streams/{id} → 404": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "NOT_FOUND",
                        "message": "Resource not found",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "HEAD /api/streams/{id} → 503": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "SERVICE_UNAVAILABLE",
                        "message": "Service temporarily unavailable",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "PATCH /api/streams/{id}/status → 200": {
            "application/json": {
                "default": {
                    "success": True,
                    "data": {
                        "id": "stream-abc123",
                        "sender": "GAAZI4TCR3TY5OJHCTJC2A4QSY6CJWJH5IAJTGKIN2ER7LBNVKOCCWN",
                        "recipient": "GCEZWKCA5VLDNRLN3RPRJMRZOX3Z6G5CHCGZCP2J7F1NRQKQOHP3OGN",
                        "depositAmount": "1000000.0000000",
                        "streamedAmount": "0.0000000",
                        "remainingAmount": "1000000.0000000",
                        "ratePerSecond": "0.0000116",
                        "startTime": 1700000000,
                        "endTime": 0,
                        "status": "paused",
                        "contractId": "api-created",
                        "transactionHash": "0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b",
                        "eventIndex": 0,
                        "createdAt": "2026-01-01T00:00:00.000Z",
                        "updatedAt": "2026-01-01T00:00:00.000Z",
                    },
                    "meta": {
                        "timestamp": "2026-01-01T00:00:00.000Z",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "PATCH /api/streams/{id}/status → 400": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "VALIDATION_ERROR",
                        "message": "Request validation failed",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "PATCH /api/streams/{id}/status → 404": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "NOT_FOUND",
                        "message": "Resource not found",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "PATCH /api/streams/{id}/status → 409": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "CONFLICT",
                        "message": "Resource conflict",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "PATCH /api/streams/{id}/status → 503": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "SERVICE_UNAVAILABLE",
                        "message": "Service temporarily unavailable",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "POST /api/auth/session → 200": {
            "application/json": {
                "default": {
                    "token": "eyJ...",
                    "user": {
                        "address": "GAAZI4...",
                        "role": "viewer",
                    },
                },
            },
        },
        "POST /api/auth/session → 400": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "VALIDATION_ERROR",
                        "message": "Request validation failed",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "POST /api/auth/session → 401": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "UNAUTHORIZED",
                        "message": "Authentication required to access this resource",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /api/audit → 200": {
            "application/json": {
                "default": {
                    "success": True,
                    "data": {
                        "entries": [
                            {
                                "seq": 1,
                                "timestamp": "2026-01-01T00:00:00.000Z",
                                "action": "stream.create",
                                "resourceType": "stream",
                                "resourceId": "stream-abc123",
                                "correlationId": "req_abc123",
                                "meta": None,
                            },
                        ],
                        "total": 1,
                    },
                    "meta": {
                        "timestamp": "2026-01-01T00:00:00.000Z",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /api/audit → 401": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "UNAUTHORIZED",
                        "message": "Authentication required to access this resource",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /api/audit → 403": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "FORBIDDEN",
                        "message": "Insufficient permissions to access this resource",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /api/privacy/policy → 200": {
            "application/json": {
                "default": {
                    "service": "fluxora-backend",
                    "version": "0.1.0",
                    "piiPolicy": {
                        "summary": "Fluxora stores only chain-derived pseudonymous data (Stellar public keys and on-chain amounts).",
                        "dataClassifications": [
                            {
                                "level": "PUBLIC",
                                "description": "Stellar public keys and amounts",
                            },
                        ],
                        "fieldPolicies": {
                            "streamFields": {},
                            "requestFields": {},
                        },
                        "retentionSchedule": [],
                        "trustBoundaries": [
                            {
                                "actor": "Anonymous client",
                                "description": "Unauthenticated public internet request.",
                                "allowed": [
                                    "Read public stream list and individual stream details",
                                ],
                                "denied": [
                                    "Create or mutate stream records (future: requires auth)",
                                ],
                            },
                        ],
                    },
                    "_links": {
                        "self": "/api/privacy/policy",
                    },
                },
            },
        },
        "GET /api/privacy/retention → 200": {
            "application/json": {
                "default": {
                    "retentionSchedule": [
                        {
                            "dataClass": "STREAM_METADATA",
                            "retentionDays": 365,
                        },
                        {
                            "dataClass": "AUDIT_LOG",
                            "retentionDays": 90,
                        },
                    ],
                    "_links": {
                        "self": "/api/privacy/retention",
                        "fullPolicy": "/api/privacy/policy",
                    },
                },
            },
        },
        "GET /api/admin/status/read-only → 200": {
            "application/json": {
                "default": {
                    "success": True,
                    "data": {
                        "pauseFlags": {
                            "streamCreation": False,
                            "ingestion": False,
                        },
                    },
                    "meta": {
                        "timestamp": "2026-01-01T00:00:00.000Z",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /api/admin/status → 200": {
            "application/json": {
                "default": {
                    "success": True,
                    "data": {
                        "pauseFlags": {
                            "streamCreation": False,
                            "ingestion": False,
                        },
                        "reindex": {
                            "status": "idle",
                            "lastCompletedAt": None,
                        },
                    },
                    "meta": {
                        "timestamp": "2026-01-01T00:00:00.000Z",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /api/admin/status → 401": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "UNAUTHORIZED",
                        "message": "Authentication required to access this resource",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /api/admin/pause → 200": {
            "application/json": {
                "default": {
                    "success": True,
                    "data": {
                        "streamCreation": False,
                        "ingestion": False,
                    },
                    "meta": {
                        "timestamp": "2026-01-01T00:00:00.000Z",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /api/admin/pause → 401": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "UNAUTHORIZED",
                        "message": "Authentication required to access this resource",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "PUT /api/admin/pause → 200": {
            "application/json": {
                "default": {
                    "success": True,
                    "data": {
                        "message": "Pause flags updated.",
                        "pauseFlags": {
                            "streamCreation": True,
                            "ingestion": False,
                        },
                    },
                    "meta": {
                        "timestamp": "2026-01-01T00:00:00.000Z",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "PUT /api/admin/pause → 400": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "VALIDATION_ERROR",
                        "message": "Request validation failed",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "PUT /api/admin/pause → 401": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "UNAUTHORIZED",
                        "message": "Authentication required to access this resource",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "PUT /api/admin/pause → 503": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "SERVICE_UNAVAILABLE",
                        "message": "Service temporarily unavailable",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /api/admin/reindex → 200": {
            "application/json": {
                "default": {
                    "success": True,
                    "data": {
                        "status": "idle",
                        "lastCompletedAt": None,
                        "progress": None,
                    },
                    "meta": {
                        "timestamp": "2026-01-01T00:00:00.000Z",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /api/admin/reindex → 401": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "UNAUTHORIZED",
                        "message": "Authentication required to access this resource",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "POST /api/admin/reindex → 202": {
            "application/json": {
                "default": {
                    "success": True,
                    "data": {
                        "message": "Reindex started.",
                        "reindex": {
                            "status": "running",
                            "startedAt": "2026-01-01T00:00:00.000Z",
                            "progress": 0,
                        },
                    },
                    "meta": {
                        "timestamp": "2026-01-01T00:00:00.000Z",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "POST /api/admin/reindex → 401": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "UNAUTHORIZED",
                        "message": "Authentication required to access this resource",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "POST /api/admin/reindex → 409": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "CONFLICT",
                        "message": "Resource conflict",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "POST /api/admin/ws/disconnect → 200": {
            "application/json": {
                "default": {
                    "success": True,
                    "data": {
                        "message": "WebSocket subscribers disconnected.",
                        "stream_id": "stream-abc123",
                        "disconnectedCount": 3,
                    },
                    "meta": {
                        "timestamp": "2026-01-01T00:00:00.000Z",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "POST /api/admin/ws/disconnect → 400": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "VALIDATION_ERROR",
                        "message": "Request validation failed",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "POST /api/admin/ws/disconnect → 401": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "UNAUTHORIZED",
                        "message": "Authentication required to access this resource",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "POST /api/admin/ws/disconnect → 503": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "SERVICE_UNAVAILABLE",
                        "message": "Service temporarily unavailable",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /api/admin/api-keys → 200": {
            "application/json": {
                "default": {
                    "success": True,
                    "data": {
                        "apiKeys": [
                            {
                                "id": "ck1abc123",
                                "name": "my-service",
                                "prefix": "flx_a1b2",
                                "createdAt": "2026-01-01T00:00:00.000Z",
                                "lastUsedAt": None,
                                "revokedAt": None,
                            },
                        ],
                    },
                    "meta": {
                        "timestamp": "2026-01-01T00:00:00.000Z",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /api/admin/api-keys → 401": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "UNAUTHORIZED",
                        "message": "Authentication required to access this resource",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "POST /api/admin/api-keys → 201": {
            "application/json": {
                "default": {
                    "id": "ck1abc123",
                    "name": "my-service",
                    "key": "flx_a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6",
                    "prefix": "flx_a1b2",
                    "createdAt": "2026-01-01T00:00:00.000Z",
                },
            },
        },
        "POST /api/admin/api-keys → 400": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "VALIDATION_ERROR",
                        "message": "Request validation failed",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "POST /api/admin/api-keys → 401": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "UNAUTHORIZED",
                        "message": "Authentication required to access this resource",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "POST /api/admin/api-keys/{id}/rotate → 200": {
            "application/json": {
                "default": {
                    "id": "ck1abc123",
                    "name": "my-service",
                    "key": "flx_newrotatedkey000000000000000000",
                    "prefix": "flx_new",
                    "createdAt": "2026-01-01T00:00:00.000Z",
                },
            },
        },
        "POST /api/admin/api-keys/{id}/rotate → 401": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "UNAUTHORIZED",
                        "message": "Authentication required to access this resource",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "POST /api/admin/api-keys/{id}/rotate → 404": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "NOT_FOUND",
                        "message": "Resource not found",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "DELETE /api/admin/api-keys/{id} → 401": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "UNAUTHORIZED",
                        "message": "Authentication required to access this resource",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "DELETE /api/admin/api-keys/{id} → 404": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "NOT_FOUND",
                        "message": "Resource not found",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /api/admin/deprecations → 200": {
            "application/json": {
                "default": {
                    "success": True,
                    "data": [
                        {
                            "route": "/api/rate-limits/config",
                            "sunsetDate": "2026-09-30T00:00:00.000Z",
                            "link": "/docs/api/deprecation-policy.md#current-deprecations",
                            "daysUntilSunset": 93,
                        },
                    ],
                    "meta": {
                        "timestamp": "2026-01-01T00:00:00.000Z",
                    },
                },
            },
        },
        "GET /api/admin/deprecations → 401": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "UNAUTHORIZED",
                        "message": "Authentication required to access this resource",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /api/admin/deprecations → 403": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "FORBIDDEN",
                        "message": "Insufficient permissions to access this resource",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /admin/dlq → 200": {
            "application/json": {
                "default": {
                    "success": True,
                    "data": {
                        "entries": [
                            {
                                "id": "dlq_001",
                                "topic": "stream.created",
                                "payload": {
                                    "streamId": "stream-abc123",
                                },
                                "error": "RPC timeout",
                                "attempts": 2,
                                "firstFailedAt": "2026-01-01T00:00:00.000Z",
                                "lastFailedAt": "2026-01-01T00:05:00.000Z",
                                "failureHistory": [
                                    {
                                        "error": "RPC timeout",
                                        "attempt": 1,
                                        "failedAt": "2026-01-01T00:00:00.000Z",
                                        "source": "enqueue",
                                    },
                                    {
                                        "error": "signature mismatch",
                                        "attempt": 2,
                                        "failedAt": "2026-01-01T00:05:00.000Z",
                                        "source": "replay",
                                    },
                                ],
                            },
                        ],
                        "total": 1,
                        "limit": 50,
                        "offset": 0,
                        "has_more": False,
                        "suspendedTopics": [],
                    },
                    "meta": {
                        "timestamp": "2026-01-01T00:00:00.000Z",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /admin/dlq → 400": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "VALIDATION_ERROR",
                        "message": "Request validation failed",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /admin/dlq → 401": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "UNAUTHORIZED",
                        "message": "Authentication required to access this resource",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /admin/dlq → 403": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "FORBIDDEN",
                        "message": "Insufficient permissions to access this resource",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /admin/dlq/{id} → 200": {
            "application/json": {
                "default": {
                    "success": True,
                    "data": {
                        "entry": {
                            "id": "dlq_001",
                            "topic": "stream.created",
                            "payload": {
                                "streamId": "stream-abc123",
                            },
                            "error": "RPC timeout",
                            "attempts": 2,
                            "firstFailedAt": "2026-01-01T00:00:00.000Z",
                            "lastFailedAt": "2026-01-01T00:05:00.000Z",
                            "failureHistory": [
                                {
                                    "error": "RPC timeout",
                                    "attempt": 1,
                                    "failedAt": "2026-01-01T00:00:00.000Z",
                                    "source": "enqueue",
                                },
                                {
                                    "error": "signature mismatch",
                                    "attempt": 2,
                                    "failedAt": "2026-01-01T00:05:00.000Z",
                                    "source": "replay",
                                },
                            ],
                        },
                        "failureHistory": [
                            {
                                "error": "RPC timeout",
                                "attempt": 1,
                                "failedAt": "2026-01-01T00:00:00.000Z",
                                "source": "enqueue",
                            },
                            {
                                "error": "signature mismatch",
                                "attempt": 2,
                                "failedAt": "2026-01-01T00:05:00.000Z",
                                "source": "replay",
                            },
                        ],
                        "failureCount": 2,
                        "firstFailure": "RPC timeout",
                        "latestFailure": "signature mismatch",
                        "consumerSuspended": False,
                        "consecutiveFailures": 0,
                    },
                    "meta": {
                        "timestamp": "2026-01-01T00:00:00.000Z",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /admin/dlq/{id} → 401": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "UNAUTHORIZED",
                        "message": "Authentication required to access this resource",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /admin/dlq/{id} → 403": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "FORBIDDEN",
                        "message": "Insufficient permissions to access this resource",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /admin/dlq/{id} → 404": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "NOT_FOUND",
                        "message": "Resource not found",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "DELETE /admin/dlq/{id} → 200": {
            "application/json": {
                "default": {
                    "success": True,
                    "data": {
                        "message": "DLQ entry removed",
                        "id": "dlq_001",
                    },
                    "meta": {
                        "timestamp": "2026-01-01T00:00:00.000Z",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "DELETE /admin/dlq/{id} → 401": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "UNAUTHORIZED",
                        "message": "Authentication required to access this resource",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "DELETE /admin/dlq/{id} → 403": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "FORBIDDEN",
                        "message": "Insufficient permissions to access this resource",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "DELETE /admin/dlq/{id} → 404": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "NOT_FOUND",
                        "message": "Resource not found",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "POST /admin/dlq/{id}/retry → 200": {
            "application/json": {
                "default": {
                    "success": True,
                    "data": {
                        "message": "DLQ entry replayed",
                        "id": "dlq_001",
                        "topic": "stream.created",
                        "failureHistory": [
                            {
                                "error": "RPC timeout",
                                "attempt": 1,
                                "failedAt": "2026-01-01T00:00:00.000Z",
                                "source": "enqueue",
                            },
                        ],
                    },
                    "meta": {
                        "timestamp": "2026-01-01T00:00:00.000Z",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "POST /admin/dlq/{id}/retry → 400": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "VALIDATION_ERROR",
                        "message": "Request validation failed",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "POST /admin/dlq/{id}/retry → 401": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "UNAUTHORIZED",
                        "message": "Authentication required to access this resource",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "POST /admin/dlq/{id}/retry → 403": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "FORBIDDEN",
                        "message": "Insufficient permissions to access this resource",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "POST /admin/dlq/{id}/retry → 404": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "NOT_FOUND",
                        "message": "Resource not found",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /api/rate-limits → 200": {
            "application/json": {
                "default": {
                    "limit": 100,
                    "remaining": 95,
                    "resetAt": "2026-01-01T00:01:00.000Z",
                    "windowMs": 60000,
                },
            },
        },
        "GET /api/rate-limits/config → 200": {
            "application/json": {
                "default": {
                    "ip": {
                        "windowMs": 60000,
                        "max": 100,
                        "enabled": True,
                    },
                    "apiKey": {
                        "windowMs": 60000,
                        "max": 200,
                        "enabled": True,
                    },
                    "admin": {
                        "windowMs": 60000,
                        "max": 50,
                        "enabled": True,
                    },
                    "source": "default",
                },
            },
        },
        "GET /api/rate-limits/config → 401": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "UNAUTHORIZED",
                        "message": "Authentication required to access this resource",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "PUT /api/rate-limits/config → 200": {
            "application/json": {
                "default": {
                    "message": "Rate-limit config updated.",
                    "config": {
                        "ip": {
                            "windowMs": 60000,
                            "max": 200,
                            "enabled": True,
                        },
                        "apiKey": {
                            "windowMs": 60000,
                            "max": 200,
                            "enabled": True,
                        },
                        "admin": {
                            "windowMs": 60000,
                            "max": 50,
                            "enabled": True,
                        },
                    },
                },
            },
        },
        "PUT /api/rate-limits/config → 400": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "VALIDATION_ERROR",
                        "message": "Request validation failed",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "PUT /api/rate-limits/config → 401": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "UNAUTHORIZED",
                        "message": "Authentication required to access this resource",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "PUT /api/rate-limits/config → 409": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "CONFLICT",
                        "message": "Resource conflict",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "POST /internal/indexer/contract-events → 200": {
            "application/json": {
                "default": {
                    "success": True,
                    "data": {
                        "outcome": "persisted",
                        "insertedCount": 1,
                        "duplicateCount": 0,
                        "insertedEventIds": [
                            "evt-abc-001",
                        ],
                        "duplicateEventIds": [],
                    },
                    "meta": {
                        "timestamp": "2026-01-01T00:00:00.000Z",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "POST /internal/indexer/contract-events → 400": {
            "application/json": {
                "unknownTopic": {
                    "success": False,
                    "error": {
                        "code": "VALIDATION_ERROR",
                        "message": "events.0.topic: Invalid enum value. Expected one of: stream.created | stream.updated | stream.cancelled | stream.completed | stream.funded | stream.withdrawn",
                    },
                },
                "emptyBatch": {
                    "success": False,
                    "error": {
                        "code": "VALIDATION_ERROR",
                        "message": "events must not be empty",
                    },
                },
                "extraKeys": {
                    "success": False,
                    "error": {
                        "code": "VALIDATION_ERROR",
                        "message": "events.0: Unrecognized key(s) in object: 'unknownField'",
                    },
                },
            },
        },
        "POST /internal/indexer/contract-events → 401": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "UNAUTHORIZED",
                        "message": "Authentication required to access this resource",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "POST /internal/indexer/contract-events → 409": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "CONFLICT",
                        "message": "Duplicate eventId \"evt-abc-001\" within batch",
                    },
                },
            },
        },
        "POST /internal/indexer/contract-events → 413": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "PAYLOAD_TOO_LARGE",
                        "message": "Request payload exceeds the maximum allowed size",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "POST /internal/indexer/contract-events → 429": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "TOO_MANY_REQUESTS",
                        "message": "Too many requests — retry after the Retry-After header",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "POST /internal/indexer/contract-events → 503": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "SERVICE_UNAVAILABLE",
                        "message": "Service temporarily unavailable",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /internal/indexer/events → 200": {
            "application/json": {
                "default": {
                    "success": True,
                    "data": {
                        "events": [
                            {
                                "eventId": "evt-abc-001",
                                "ledger": 512345,
                                "contractId": "CBIELTK6YBZJU5UP2WWQEQPMCSB5TTNBMMKVDPKA2QCMXGFQKQKJ4AB",
                                "topic": "stream.created",
                                "txHash": "a3f4b2c1d0e9f8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f4a3",
                                "txIndex": 0,
                                "operationIndex": 0,
                                "eventIndex": 0,
                                "payload": {
                                    "streamId": "stream-abc123",
                                },
                                "happenedAt": "2026-01-01T00:00:00.000Z",
                                "ledgerHash": "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2",
                            },
                        ],
                        "total": 1,
                        "limit": 100,
                        "offset": 0,
                    },
                    "meta": {
                        "timestamp": "2026-01-01T00:00:00.000Z",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /internal/indexer/events → 401": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "UNAUTHORIZED",
                        "message": "Authentication required to access this resource",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /internal/indexer/events/replay → 200": {
            "application/json": {
                "default": {
                    "success": True,
                    "data": {
                        "events": [
                            {
                                "eventId": "evt-abc-002",
                                "ledger": 512400,
                                "contractId": "CBIELTK6YBZJU5UP2WWQEQPMCSB5TTNBMMKVDPKA2QCMXGFQKQKJ4AB",
                                "topic": "stream.cancelled",
                                "txHash": "b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5",
                                "txIndex": 1,
                                "operationIndex": 0,
                                "eventIndex": 0,
                                "payload": {
                                    "streamId": "stream-abc123",
                                },
                                "happenedAt": "2026-01-02T00:00:00.000Z",
                                "ledgerHash": "b1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6b1b2c3d4e5f6b1b2",
                            },
                        ],
                        "hasMore": False,
                        "nextAfterEventId": None,
                    },
                    "meta": {
                        "timestamp": "2026-01-01T00:00:00.000Z",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /internal/indexer/events/replay → 401": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "UNAUTHORIZED",
                        "message": "Authentication required to access this resource",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "POST /internal/webhooks/receive → 200": {
            "application/json": {
                "default": {
                    "ok": True,
                    "deliveryId": "del_01HXYZ",
                    "eventType": "stream.created",
                    "event": {
                        "streamId": "stream-abc123",
                        "amount": "1000000.0000000",
                    },
                },
            },
        },
        "POST /internal/webhooks/receive → 400": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "VALIDATION_ERROR",
                        "message": "Request validation failed",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "POST /internal/webhooks/receive → 401": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "UNAUTHORIZED",
                        "message": "Webhook signature verification failed",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "POST /internal/webhooks/receive → 409": {
            "application/json": {
                "default": {
                    "error": "duplicate_delivery",
                    "message": "Duplicate delivery id",
                    "deliveryId": "del_01HXYZ",
                },
            },
        },
        "POST /internal/webhooks/receive → 413": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "PAYLOAD_TOO_LARGE",
                        "message": "Request payload exceeds the maximum allowed size",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "POST /internal/webhooks/queue → 200": {
            "application/json": {
                "default": {
                    "ok": True,
                    "outboxId": "out_01HXYZ",
                    "message": "Webhook queued for delivery",
                },
            },
        },
        "POST /internal/webhooks/queue → 400": {
            "application/json": {
                "default": {
                    "success": False,
                    "error": {
                        "code": "VALIDATION_ERROR",
                        "message": "Request validation failed",
                        "requestId": "req_abc123",
                    },
                },
            },
        },
        "GET /metrics → 200": {
            "text/plain": {
                "default": "# HELP http_requests_total Total HTTP requests\n# TYPE http_requests_total counter\nhttp_requests_total{method=\"GET\",path=\"/health\"} 42\n",
            },
        },
    },
    "requestBodies": {
        "POST /api/streams": {
            "application/json": {
                "default": {
                    "sender": "GAAZI4TCR3TY5OJHCTJC2A4QSY6CJWJH5IAJTGKIN2ER7LBNVKOCCWN",
                    "recipient": "GCEZWKCA5VLDNRLN3RPRJMRZOX3Z6G5CHCGZCP2J7F1NRQKQOHP3OGN",
                    "depositAmount": "1000000.0000000",
                    "ratePerSecond": "0.0000116",
                    "startTime": 1700000000,
                },
            },
        },
        "PATCH /api/streams/{id}/status": {
            "application/json": {
                "default": {
                    "status": "paused",
                },
            },
        },
        "POST /api/auth/session": {
            "application/json": {},
        },
        "PUT /api/admin/pause": {
            "application/json": {
                "default": {
                    "streamCreation": True,
                    "ingestion": False,
                },
            },
        },
        "POST /api/admin/ws/disconnect": {
            "application/json": {
                "default": {
                    "stream_id": "stream-abc123",
                },
            },
        },
        "POST /api/admin/api-keys": {
            "application/json": {},
        },
        "PUT /api/rate-limits/config": {
            "application/json": {
                "default": {
                    "ip": {
                        "max": 200,
                    },
                },
            },
        },
        "POST /internal/indexer/contract-events": {
            "application/json": {
                "streamCreated": {
                    "events": [
                        {
                            "eventId": "evt-abc-001",
                            "ledger": 512345,
                            "contractId": "CBIELTK6YBZJU5UP2WWQEQPMCSB5TTNBMMKVDPKA2QCMXGFQKQKJ4AB",
                            "topic": "stream.created",
                            "txHash": "a3f4b2c1d0e9f8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f4a3",
                            "txIndex": 0,
                            "operationIndex": 0,
                            "eventIndex": 0,
                            "payload": {
                                "streamId": "stream-abc123",
                                "depositAmount": "1000000.0000000",
                                "ratePerSecond": "0.0000116",
                            },
                            "happenedAt": "2026-01-01T00:00:00.000Z",
                            "ledgerHash": "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2",
                        },
                    ],
                },
                "streamCancelled": {
                    "events": [
                        {
                            "eventId": "evt-abc-002",
                            "ledger": 512400,
                            "contractId": "CBIELTK6YBZJU5UP2WWQEQPMCSB5TTNBMMKVDPKA2QCMXGFQKQKJ4AB",
                            "topic": "stream.cancelled",
                            "txHash": "b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5",
                            "txIndex": 1,
                            "operationIndex": 0,
                            "eventIndex": 0,
                            "payload": {
                                "streamId": "stream-abc123",
                                "reason": "sender_cancelled",
                            },
                            "happenedAt": "2026-01-02T00:00:00.000Z",
                            "ledgerHash": "b1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6b1b2",
                        },
                    ],
                },
            },
        },
        "POST /internal/webhooks/receive": {
            "application/json": {},
        },
        "POST /internal/webhooks/queue": {
            "application/json": {},
        },
    },
    "parameters": {},
    "headers": {
        "GET /api/streams/{id} → 304 ETag": {
            "default": "W/\"abc123...\"",
        },
        "GET /api/streams/{id} → 304 Last-Modified": {
            "default": "Thu, 01 Jan 2026 00:00:00 GMT",
        },
    },
    "schemas": {
        "DecimalString": "1000000.0000000",
        "StellarAddress": "GAAZI4TCR3TY5OJHCTJC2A4QSY6CJWJH5IAJTGKIN2ER7LBNVKOCCWN",
        "StreamStatus": "active",
        "Stream.id": "stream-abc123",
        "Stream.startTime": 1700000000,
        "Stream.endTime": 0,
        "Stream.contractId": "api-created",
        "Stream.transactionHash": "0a1b2c3d4e...",
        "Stream.eventIndex": 0,
        "Stream.createdAt": "2026-01-01T00:00:00.000Z",
        "Stream.updatedAt": "2026-01-01T00:00:00.000Z",
        "ResponseMeta.timestamp": "2026-01-01T00:00:00.000Z",
        "ResponseMeta.requestId": "req_abc123",
        "ErrorEnvelope.error.code": "VALIDATION_ERROR",
        "ErrorEnvelope.error.message": "Validation failed",
        "WebSocketSubscriptionFilter.stream_id": "placeholder-stream-id",
        "WebSocketSubscriptionFilter.streamId": "placeholder-stream-id",
        "WebSocketSubscriptionFilter.recipient_address.allOf[1]": "GAAZI4TCR3TY5OJHCTJC2A4QSY6CJWJH5IAJTGKIN2ER7LBNVKOCCWN7",
        "WebSocketSubscriptionFilter.recipientAddress.allOf[1]": "GAAZI4TCR3TY5OJHCTJC2A4QSY6CJWJH5IAJTGKIN2ER7LBNVKOCCWN7",
        "WebSocketSubscribeMessage": {
            "type": "subscribe",
            "filter": {
                "stream_id": "placeholder-stream-id",
            },
        },
        "WebSocketUnsubscribeMessage": {
            "type": "unsubscribe",
            "filter": {
                "recipient_address": "GAAZI4TCR3TY5OJHCTJC2A4QSY6CJWJH5IAJTGKIN2ER7LBNVKOCCWN7",
            },
        },
        "StreamCursorToken": "eyJ2IjoxLCJsYXN0SWQiOiJzdHJlYW0tYWJjMTIzIn0",
        "StreamListPage.has_more": True,
        "StreamListPage.next_cursor": "eyJ2IjoxLCJsYXN0SWQiOiJzdHJlYW0tYWJjMTIzIn0",
        "StreamListPage.total": 42,
        "TrustBoundary.actor": "Anonymous client",
        "TrustBoundary.description": "Unauthenticated public internet request.",
        "TrustBoundary.allowed": [
            "Read public stream list and individual stream details",
        ],
        "TrustBoundary.denied": [
            "Create or mutate stream records (future: requires auth)",
        ],
        "DeprecatedRouteEntry.route": "/api/rate-limits/config",
        "DeprecatedRouteEntry.sunsetDate": "2026-09-30T00:00:00.000Z",
        "DeprecatedRouteEntry.link": "/docs/api/deprecation-policy.md#current-deprecations",
        "DeprecatedRouteEntry.daysUntilSunset": 93,
        "ContractEventSchema.eventId": "evt-abc-001",
        "ContractEventSchema.ledger": 512345,
        "ContractEventSchema.contractId": "CBIELTK6YBZJU5UP2WWQEQPMCSB5TTNBMMKVDPKA2QCMXGFQKQKJ4AB",
        "ContractEventSchema.topic": "stream.created",
        "ContractEventSchema.txHash": "a3f4b2c1d0e9f8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f4a3",
        "ContractEventSchema.txIndex": 0,
        "ContractEventSchema.operationIndex": 0,
        "ContractEventSchema.eventIndex": 0,
        "ContractEventSchema.payload": {
            "streamId": "stream-abc123",
            "depositAmount": "1000000.0000000",
            "ratePerSecond": "0.0000116",
        },
        "ContractEventSchema.happenedAt": "2026-01-01T00:00:00.000Z",
        "ContractEventSchema.ledgerHash": "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2",
    },
}
