/**
 * src/metrics/wsBackpressure.ts
 *
 * Per-client WebSocket backpressure gauges, subscription cardinality
 * metrics, and micro-batching counters exposed to Prometheus.
 *
 * Four metrics are emitted for live WebSocket subscribers on the
 * `/ws/streams` endpoint:
 *
 *   - `fluxora_ws_backpressure_buffered_bytes{connection_id="…"}` — current
 *     `ws.bufferedAmount` per client, useful for finding a specific slow
 *     peer.  This is the primary, bounded-cardinality gauge required by the
 *     per-client observability feature.
 *   - `fluxora_ws_max_buffered_bytes`     — max bufferedAmount across all
 *     live clients (low cardinality, suitable for dashboards/alerts).
 *   - `fluxora_ws_slow_clients`           — count of clients whose buffered
 *     bytes exceed the configurable warning threshold (default 1 MiB).
 *   - `fluxora_ws_stream_subscriber_count{stream_id="…"}` — subscriber
 *     count for the top-N streams by fan-out size (default N=20). Reports
 *     only the most-subscribed streams so operators can spot a single hot
 *     stream driving disproportionate broadcast fan-out before it causes
 *     backpressure incidents.
 *
 * ### Micro-batching counters (three series)
 *
 *   - `fluxora_ws_batch_flush_total`         — total flush operations (each
 *     flush produces one outbound `stream_update_batch` frame per client).
 *   - `fluxora_ws_batch_events_coalesced_total` — total individual events
 *     that were coalesced across all flushes.  Comparing this to
 *     `fluxora_ws_batch_flush_total` gives the average batch size.
 *   - `fluxora_ws_batch_size_exceeded_total` — flushes where the batch hit
 *     `WS_BATCH_MAX_SIZE` before the flush window expired (early ejection).
 *
 * The per-client gauge is updated by a poll loop so the value reflects the
 * actual kernel/OS send-buffer state, not just the snapshot taken during a
 * `deliverBatch` call.  Series for disconnected clients are explicitly removed
 * via `removeWsClientBackpressureGauge` to prevent unbounded label
 * accumulation.  See `docs/observability.md` for the labeling-choice rationale
 * and bounded-cardinality guarantee.
 */

import { Counter, Gauge, Histogram } from 'prom-client';
import { registry } from '../metrics.js';
import type { StreamHub } from '../ws/hub.js';

/**
 * Default warning threshold for "slow client" classification.
 * Mirrors `BACKPRESSURE_DROP_BYTES` in `src/ws/hub.ts` (1 MiB) by default,
 * but can be overridden via the `slowThresholdBytes` parameter of
 * `collectWsBackpressureMetrics` to e.g. trigger before the hub actively
 * drops frames.
 */
export const DEFAULT_WS_SLOW_CLIENT_BYTES = 1 * 1024 * 1024;

/**
 * Default poll interval for the backpressure collector. Five seconds is a
 * reasonable balance between metric freshness and CPU churn when there are
 * many concurrent connections — Prometheus typically scrapes every 15s, so
 * 5s-poll values are always at most one poll-stale in the worst case.
 */
export const DEFAULT_WS_BACKPRESSURE_INTERVAL_MS = 5_000;

// ── Backpressure gauges ────────────────────────────────────────────────────────

/**
 * Maximum number of streams reported by the subscription cardinality gauge.
 * Capping this prevents unbounded Prometheus label cardinality when many
 * streams each have a handful of subscribers — only the top-N most-subscribed
 * streams are exposed. Streams that drop out of the top-N between collection
 * cycles have their gauge series removed so stale labels don't persist.
 */
export const DEFAULT_WS_STREAM_CARDINALITY_TOP_N = 20;

/**
 * Per-client backpressure gauge. Labels are intentionally limited to
 * `connection_id` — a UUID v4 generated by the server, low cardinality and
 * free of PII.
 *
 * Cardinality guarantee: at most one time-series per *currently connected*
 * client. Series are removed when the client disconnects
 * (`removeWsClientBackpressureGauge`) to prevent unbounded memory growth
 * in long-running processes.  The label set is therefore bounded by the
 * peak concurrent-connection count, not by total connections over time.
 *
 * @security The `connection_id` label is a server-generated UUID v4. It
 *   never contains client IP, account subject, JWT `sub`, request ID, or
 *   any other identifier that could be used to fingerprint or correlate a
 *   particular user.  The bounded-cardinality design prevents an attacker
 *   from inflating Prometheus memory by repeatedly reconnecting — each
 *   reconnect simply replaces the prior series for that one seat.
 */
export const wsClientBufferedBytes =
  (registry.getSingleMetric('fluxora_ws_backpressure_buffered_bytes') as Gauge<'connection_id'>) ||
  new Gauge<'connection_id'>({
    name: 'fluxora_ws_backpressure_buffered_bytes',
    help: 'Current ws.bufferedAmount per connected WebSocket client on /ws/streams. Bounded by connection_id (server-generated UUID v4); series removed on disconnect.',
    labelNames: ['connection_id'] as const,
    registers: [registry],
  });

/** Maximum bufferedAmount observed across all live WebSocket clients. */
export const wsMaxBufferedBytes =
  (registry.getSingleMetric('fluxora_ws_max_buffered_bytes') as Gauge) ||
  new Gauge({
    name: 'fluxora_ws_max_buffered_bytes',
    help: 'Maximum ws.bufferedAmount observed across all live WebSocket clients',
    registers: [registry],
  });

/**
 * Register a metric safely, reusing an existing registration if one exists.
 * This is necessary because tests that use `vi.resetModules()` may re-import
 * this module multiple times, which would otherwise throw "already registered".
 */
function metric<T>(name: string, factory: () => T): T {
  const existing = registry.getSingleMetric(name);
  if (existing) return existing as unknown as T;
  return factory();
}

/**
 * Histogram tracking the age of the oldest event in a batch when flushed.
 * Buckets are tuned specifically for sub-second to low-second micro-batching windows.
 */
export const wsBroadcastBatchFlushLatencySeconds = metric(
  'fluxora_ws_broadcast_batch_flush_seconds',
  () =>
    new Histogram({
      name: 'fluxora_ws_broadcast_batch_flush_seconds',
      help: 'Latency (in seconds) from the oldest event enqueued to the moment the batch is flushed to WebSockets.',
      buckets: [0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5],
    }),
);

/**
 * Helper to record batch flush latency in seconds.
 */
export function recordWsBroadcastBatchFlushLatency(durationSeconds: number): void {
  if (typeof durationSeconds === 'number' && isFinite(durationSeconds) && durationSeconds >= 0) {
    wsBroadcastBatchFlushLatencySeconds.observe(durationSeconds);
  }
}


export const wsSlowClients = metric(
  'fluxora_ws_slow_clients',
  () =>
    new Gauge({
      name: 'fluxora_ws_slow_clients',
      help: 'Number of WebSocket clients whose bufferedAmount exceeds the slow threshold.',
    }),
);

export const wsMaxSubscriptionsPerConnection = metric(
  'fluxora_ws_max_subscriptions_per_connection',
  () =>
    new Gauge({
      name: 'fluxora_ws_max_subscriptions_per_connection',
      help: 'Configured maximum number of subscriptions a single WebSocket connection may hold.',
      registers: [registry],
    }),
);

export const wsMaxOutboundQueuePerConnection = metric(
  'fluxora_ws_max_outbound_queue_per_connection',
  () =>
    new Gauge({
      name: 'fluxora_ws_max_outbound_queue_per_connection',
      help: 'Configured maximum outbound queue depth for a single WebSocket connection.',
      registers: [registry],
    }),
);

export const wsMaxOutboundQueueBytesPerConnection = metric(
  'fluxora_ws_max_outbound_queue_bytes_per_connection',
  () =>
    new Gauge({
      name: 'fluxora_ws_max_outbound_queue_bytes_per_connection',
      help: 'Configured maximum retained outbound queue bytes for a single WebSocket connection.',
      registers: [registry],
    }),
);

export const wsMaxInboundMessageBytes = metric(
  'fluxora_ws_max_inbound_message_bytes',
  () =>
    new Gauge({
      name: 'fluxora_ws_max_inbound_message_bytes',
      help: 'Configured maximum inbound WebSocket payload size in bytes per connection.',
      registers: [registry],
    }),
);

export const wsSubscriptionLimitViolationsTotal = metric(
  'fluxora_ws_subscription_limit_violations_total',
  () =>
    new Counter({
      name: 'fluxora_ws_subscription_limit_violations_total',
      help: 'Number of times a client attempted to exceed the per-connection subscription cap.',
      registers: [registry],
    }),
);

export const wsOutboundQueueLimitViolationsTotal = metric(
  'fluxora_ws_outbound_queue_limit_violations_total',
  () =>
    new Counter({
      name: 'fluxora_ws_outbound_queue_limit_violations_total',
      help: 'Number of times an outbound queue rejection dropped a queued message because the per-connection queue was full.',
      registers: [registry],
    }),
);

export const wsInboundMessageSizeLimitViolationsTotal = metric(
  'fluxora_ws_inbound_message_size_limit_violations_total',
  () =>
    new Counter({
      name: 'fluxora_ws_inbound_message_size_limit_violations_total',
      help: 'Number of inbound WebSocket messages rejected for exceeding the configured maximum bytes.',
      registers: [registry],
    }),
);

export function setWsResourceLimitMetrics(config: {
  maxSubscriptionsPerConnection: number;
  maxOutboundQueuePerConnection: number;
  maxOutboundQueueBytesPerConnection: number;
  maxInboundMessageBytes: number;
}): void {
  wsMaxSubscriptionsPerConnection.set(config.maxSubscriptionsPerConnection);
  wsMaxOutboundQueuePerConnection.set(config.maxOutboundQueuePerConnection);
  wsMaxOutboundQueueBytesPerConnection.set(config.maxOutboundQueueBytesPerConnection);
  wsMaxInboundMessageBytes.set(config.maxInboundMessageBytes);
}

// ── Subscription cardinality gauge ────────────────────────────────────────

export const wsStreamSubscriberCount = metric(
  'fluxora_ws_stream_subscriber_count',
  () =>
    new Gauge({
      name: 'fluxora_ws_stream_subscriber_count',
      help: 'Number of subscribers per stream (top-N capped).',
      labelNames: ['stream_id'],
    }),
);

// ── Batch flush counters ──────────────────────────────────────────────────

export const wsBatchFlushTotal = metric(
  'fluxora_ws_batch_flush_total',
  () =>
    new Counter({
      name: 'fluxora_ws_batch_flush_total',
      help: 'Total number of batch flushes (one frame emitted per flush).',
    }),
);

export const wsBatchEventsCoalescedTotal = metric(
  'fluxora_ws_batch_events_coalesced_total',
  () =>
    new Counter({
      name: 'fluxora_ws_batch_events_coalesced_total',
      help: 'Total number of individual events coalesced across all batch flushes.',
    }),
);

export const wsBatchSizeExceededTotal = metric(
  'fluxora_ws_batch_size_exceeded_total',
  () =>
    new Counter({
      name: 'fluxora_ws_batch_size_exceeded_total',
      help: 'Number of batch flushes triggered early by hitting the max-size cap.',
    }),
);

// ── Collection ────────────────────────────────────────────────────────────

/**
 * Collect all WebSocket backpressure and subscription-cardinality metrics
 * from the hub and publish them to Prometheus gauges.
 *
 * Should be called on a periodic interval (typically every 5 s).  The
 * function is designed to be resilient — missing hub methods, undefined
 * socket properties, and invalid parameter values are all handled without
 * throwing.
 *
 * @param hub                   StreamHub instance (or stub) providing
 *                              `_getClients` and `_getStreamSubscriptions`.
 * @param slowThresholdBytes    Buffered-amount threshold above which a client
 *                              is classified as "slow".  Clamped to 0.
 * @param topN                  Maximum number of stream-subscription-cardinality
 *                              series to emit.  Clamped to 1.
 */
export function collectWsBackpressureMetrics(
  hub: {
    _getClients?: () => IterableIterator<[unknown, { id: string }]>;
    _getStreamSubscriptions?: () => ReadonlyMap<string, Set<unknown>>;
  },
  slowThresholdBytes: number = DEFAULT_WS_SLOW_CLIENT_BYTES,
  topN: number = DEFAULT_WS_STREAM_CARDINALITY_TOP_N,
): void {
  const effectiveSlowThreshold = slowThresholdBytes >= 0 ? slowThresholdBytes : 0;
  const effectiveTopN = topN >= 1 ? topN : 1;

  const clientIterator = hub._getClients?.();
  if (clientIterator) {
    let max = 0;
    let slowCount = 0;

    for (const [ws, state] of clientIterator) {
      if (!state || !state.id) continue;

      const socket = ws as { readyState?: number; bufferedAmount?: number };
      if (socket.readyState !== 1) continue;

      const ba = typeof socket.bufferedAmount === 'number' && socket.bufferedAmount >= 0
        ? socket.bufferedAmount
        : 0;
      wsClientBufferedBytes.set({ connection_id: state.id }, ba);

      if (ba > max) max = ba;
      if (ba > effectiveSlowThreshold) slowCount++;
    }

    wsMaxBufferedBytes.set(max);
    wsSlowClients.set(slowCount);
  }

  const streamSubs = hub._getStreamSubscriptions?.();
  if (streamSubs) {
    const sorted = Array.from(streamSubs.entries())
      .map(([id, set]) => [id, set?.size ?? 0] as const)
      .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
      .slice(0, effectiveTopN);

    wsStreamSubscriberCount.reset();
    for (const [id, count] of sorted) {
      wsStreamSubscriberCount.set({ stream_id: id }, count);
    }
  }
}

export function removeWsClientBackpressureGauge(connectionId: string): void {
  wsClientBufferedBytes.remove({ connection_id: connectionId });
}

export function resetWsBackpressureMetrics(): void {
  wsClientBufferedBytes.reset();
  wsMaxBufferedBytes.reset();
  wsSlowClients.reset();
  wsStreamSubscriberCount.reset();
  wsBatchFlushTotal.reset();
  wsBatchEventsCoalescedTotal.reset();
  wsBatchSizeExceededTotal.reset();
  wsBroadcastBatchFlushLatencySeconds.reset();
}
